cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('cart_needs', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

cart/forms.py
from django import forms


class AddProductForm(forms.Form):
    quantity = forms.IntegerField(label="수량 ")
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from shop.models import Product
from coupon.forms import AddCouponForm
from .forms import AddProductForm
from .cart import Cart
from shop.models import Restaurant


@require_POST
def add(request, product_id):
    cart = Cart(request)
    restaurant = Restaurant()
    product = get_object_or_404(Product, id=product_id)
    add_to_cart = AddProductForm(initial={'quantity': 1})

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity': product['quantity'], 'is_update': True})
    return render(request, 'cart/detail.html', {'cart': cart, 'add_coupon': add_coupon})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Shopping cart
{% endblock %}

{% block content %}

<link rel = "stylesheet" href = "{% static 'css/detail.css' %}">

<style>
    #titlefont {
        font-size: 200%;
        font-weight: bold;
    }
    #subfont {
        font-size: 150%;
        font-weight: bold;
    }
    #totalpricefont {
        font-size: 200%;
        font-weight: bold;
        color: #00be68;
    }
    #totalwordfont {
        font-size: 150%;
        font-weight: 300%;
    }
    #font15 {
        font-size: 150%;
    }
    .btn-success {
        background-color: #2A6049;
        border-color: #2A6049;
        color: white;
    }

    .btn-success:focus {
        border-color: #2A6049;
        border-color: #2A6049;
        color: white;    
    }
    .btn-success:hover {
        border-color: #2A6049;
        background-color: #2A6049;
        color: white; 
    }            
</style>

<div class = "box-container">

    <div class = "cartword">
        <p id = "titlefont">장바구니</p>
    </div>

    <div class = "cartsituation">
        <p class = "text-center">
            <img src = "{% static '/img/cart001.png' %}" alt = "cart01" style = "height: 80px; ">
        </p>
    </div>

    <div class = "cartlist">

        <table class="table table-striped">

            <colgroup>
                <col width = "15%">
                <col width = "13%">
                <col width = "30%">
                <col width = "15%">
                <col width = "15%">
                <col width = "*">
            </colgroup>

            <thead>
                <tr>
                    <th scope="col">이미지</th>
                    <th scope="col">상품</th>
                    <th scope="col">수량</th>
                    <th scope="col">삭제</th>
                    <th scope="col">상품 가격</th>
                    <th scope="col">가격</th>
                </tr>
            </thead>

            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <th scope="row">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" class="img-thumbnail">
                        </a>
                    </th>
                    <td style="vertical-align: middle;">{{ product.name }}</td>
                    <td style="vertical-align: middle;">
                        <form action="{% url 'cart:product_add' product.id %}" method="post">
                            {{ item.quantity_form.quantity }}
                            {{ item.quantity_form.is_update }}
                            <input type="submit" class="btn btn-success" value="수량변경">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td style="vertical-align: middle;"><a href="{% url 'cart:product_remove' product.id %}" style="color:black">삭제하기</a></td>
                    <!-- 원화로 변경 -->
                    <td class="num" style="vertical-align: middle;">{{ item.price }}원</td>
                    <td class="num" style="vertical-align: middle;">{{ item.total_price }}원</td>
                </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <!-- 원화로 변경 -->
                    <td >{{ cart.get_product_total }}원</td>
                </tr>
                <tr>
                        <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.amount }}원)</td>
                    <td colspan="4"></td>
                    <td >- {{ cart.get_discount_total}}원</td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>합계금액</td>
                <td colspan="4"></td>
                <!-- 원화로 변경 -->
                <td class="num">{{ cart.get_total_price }}원</td> 
            </tr>
            </tbody>

        </table>

    </div>

    <div class = "checkout">
        <p class="text-center">
            <a href='{% url "shop:product_all" %}' class="btn btn-secondary btn-lg">쇼핑하러 가기</a>
            <a href='{% url "orders:order_create" %}' class="btn btn-success btn-lg">상품 구매</a>
        </p>
    </div>

</div>

{% endblock %}