shop/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'shop'

urlpatterns = [
    path('', landingpage, name="home"),
    path('envigoods/', envigoods, name="envigoods"),
    path('serviceintroduce/', serviceintroduce, name="serviceintroduce"),
    path('main/', restaurant_in_category, name='product_all'),
    path('<slug:category_slug>/', restaurant_in_category, name='restaurant_in_category'),
    path('main/<slug:restaurant_slug>/', product_in_restaurant, name='product_in_restaurant'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('sellerPage/register/', ProductRegister.as_view(), name='product_register'),

    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
    path('deletecomment/<int:comment_id>', deletecomment, name='deletecomment'),

]

shop/templates/product_register.html
{% extends 'base.html' %}

{% block content %}
<div class = "row mt-5">
    <div class = "col-12 text-center">
        <h1>상품 등록</h1>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-12">
        <form method = "POST" action = "{% url 'shop:product_register' %}">
            {% csrf_token %}
            {% for field in form %}
            <div class = "form-group">
                <label for = "{{field.id_for_label}}">{{field.label}}</label>
                {% ifequal field.name 'description' %}
                <textarea class = "form-control" name = "{{field.name}}" id = "{{field.id_for_label}}"></textarea>
                {% else %}
                <input type = "{{field.field.widget.input_type }}" class = "form-control" name = "{{field.name}}"
                id = "{{field.id_for_label}}" placeholder="{{field.label}}" name = "{{field.name}}">
                {% endifequal %}
            </div>
            {% if field.errors %}
            <span style = "color:red">{{field.errors}}</span>
            {% endif %}
            {% endfor %}

            <button type = "submit" class = "btn btn-success">상품등록</button>
        </form>
    </div>
</div>
{% endblock %}