order/urls.py
from django.urls import path

from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('payment/complete/', order_complete, name='order_complete'),
    path('payment/', order_payment, name='order_payment'),
]

order/templates/order/create.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block title %}
Checkout

{% endblock %}

{% block script %}
<script type="text/javascript">
    csrf_token = '{{ csrf_token }}';
    order_create_url = '{% url "orders:order_create_ajax" %}';
    order_checkout_url = '{% url "orders:order_checkout" %}';
    order_validation_url = '{% url "orders:order_validation" %}';
    order_complete_url = '{% url "orders:order_complete" %}';
</script>

<script src="https://cdn.iamport.kr/js/iamport.payment-1.1.5.js" type="text/javascript"></script>

{% load static %}
<script src="{% static 'js/checkout.js' %}" type="text/javascript"></script>


{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/create.css' %}">

<style>
    #titlefont {
        font-size: 200%;
        font-weight: bold;
    }
    #totalpricefont {
        font-size: 200%;
        font-weight: bold;
        color: #2a6049;
    }
    #totalwordfont {
        font-size: 150%;
        font-weight: 300%;
    }
    #line {
        border-bottom: 1px lightgray;
    }
    #font15 {
        font-size: 130%;
    }
    .btn-success {
        background-color: #2A6049;
        border-color: #2A6049;
        color: white;
    }
    .btn-success:focus {
        border-color: #2A6049;
        border-color: #2A6049;
        color: white;    
    }
    .btn-success:hover {
        border-color: #2A6049;
        background-color: #2A6049;
        color: white; 
    }
</style>

<div class="box-container">

    <div class="orderword">
        <p id="titlefont">주문현황</p>
    </div>

    <div class="finalordersituation">
        <p class="text-center">
            <img src="{% static '/img/cart002.png' %}" alt="cart002" style="height: 80px; ">
        </p>
    </div>

    <div class="finalorderlist">

        <table id="table1-layout">
            <style>
                th { height: 4rem;}
            </style>

            <colgroup>
                <col width="20%">
                <col width="20%">
                <col width="15%">
                <col width="20%">
                <col width="*">
            </colgroup>

            <thead>
            <tr>
                <th scope="col">이미지</th>
                <th scope="col">상품</th>
                <th scope="col">수량</th>
                <th scope="col">WBpoint</th>
                <th scope="col">가격</th>
            </tr>
            </thead>

            <tbody>

            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img-thumbnail" style="width:80%;">
                    </a>
                </th>
                <td id="font15">{{ item.product.name }}</td>
                <td id="font15">{{ item.quantity }} 개</td>
                <td id="font15">{{item.quantity|mul:item.price|div:10}} point</td>
                <!-- 원화로 변경 -->
                <td class="num" id="font15"><span id="amount3r" value="100">{{item.total_price}}원</span></td>
            </tr>

            {% endwith %}
            {% endfor %}

            {% if cart.coupon %}
            <li class="list-group-item">

                "{{ cart.coupon.code }}" ({{ cart.coupon.amount }}% off)

                <span>- ${{ cart.get_total_discount}}</span>
            </li>
            {% endif %}

            </tbody>

        </table>

    </div>

    <div class="finalorder">

        <table id="table2-layout">

            <colgroup>
                <col width="50%">
                <col width="*">
            </colgroup>

            <tr>
                <td rowspan="4" id="titlefont">총 주문금액</td>
                <td><span>주문상품 수</span><span style="float: right;">{{final}}개</span></td>
            <tr>
                <td><span>WB 포인트 적립 금액</span><span style="float: right;">{{env_point}}점</span></td>
            </tr>
            <tr>
                <td><span id="totalwordfont">최종결제금액</span><span id="totalpricefont" style="float: right;">{{cart.get_total_price}}원</span>
                </td>
            </tr>

        </table>

    </div>

    <div class="checkout">

        <p>
            이용약관, 개인정보 수집 및 이용, 개인정보 제3자 제공, 전자금융거래 이용약관, 만 14세 이상 이용자 내용 확인하였으며 결제에 동의합니다.
        </p>

        <!-- form에 class 추가 -->
        <form action='{% url "orders:order_payment" %}' method="POST" class="order-form">
            {{form.as_p}}
            {% csrf_token %}
            <!-- hidden field 추가-->
            <input type="hidden" name="pre_order_id" value="0">
            <input type="hidden" name="amount" id="amount" value="{{ cart.get_total_price}}">
            <button type="submit" class="btn btn-success btn-lg float-right" style="width: 150px; ">결제하기</button>
        </form>

    </div>

</div>

</div>

{% endblock %}

order/templates/order/created.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Order Complete
{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/created.css' %}">

<title>OrderComplete</title>

<style>
    #fontsize15 {font-size: 150%; }
    #green { color: #00be68; }
    #finalfont{
        font-size:150%;
    color: #00be68;}
</style>

<div class="box-container">

    <div class = "ordercomplete" style="background-color:#F2F2F2;">

        <ul id = "fontsize15" style = "list-style: none; ">
            <li>주문이 완료되었습니다.</li><br>
            <li><span id="green">{{user.nickname}}</span> 님의 주문으로</li>
            <li>Webeing과 함께 환경보호에 동참하였습니다!</li><br>
            <li>지금까지 환경을 위해</li>
            <li><span id="green">{{user.env_money}}</span>원을 투자하셨습니다.</li><br>
            <li>저희 위빙을 통하여 절약된 금액은</li><br>
            <li id="finalfont">총 {{total}}원 입니다.</li>
        </ul>

    </div>

</div>

<div id = "gohome" style="margin-top: 3rem;">
    <a href = "{% url 'shop:product_all' %}">
        <p class="text-center">
            <button type="button" class="btn btn-success" style="width:300px;">홈으로 가기</button>
        </p>
    </a>
</div>

{% endblock %}

order/templates/order/payment.html
{% extends 'base.html' %}
{% block content %}

{% with product=item.product %}

<head>
    <meta charset="utf-8"/>
    <div id = "test" style ="color : white">{{cart.get_total_price|floatformat:"0"}}</div>
    <div id = "order_name" style ="color : white">{{ product.name }} 외 {{ item.quantity }} 개</div>
    <div id = "buyer_name" style ="color : white">{{ user.nickname }} </div>
    <div id = "buyer_email" style ="color : white">{{ user.email }} </div>
    <div id = "buyer_phone_number" style ="color : white">{{ user.phone_number }} </div>    
    <script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="http://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <script>
        (function () {
            var IMP = window.IMP;
            var code = "imp00459409";
            IMP.init(code);
            var $form = $('.list-group-item');
            var params = {
                name: $form.find('[name=name]').val(),
                amount: $form.find('[name=amount11]').val(),
            };
            var test1 = document.getElementById("test").innerHTML;
            var test2 = document.getElementById("order_name").innerHTML;
            var test3 = document.getElementById("buyer_name").innerHTML;
            var test4 = document.getElementById("buyer_email").innerHTML;
            var test5 = document.getElementById("buyer_phone_number").innerHTML;

            console.log(test1)
            // 결제요청
            IMP.request_pay({
                // name과 amount만 있어도 결제 진행가능
                pg: 'html5_inicis', // pg 사 선택
                pay_method: 'card',
                merchant_uid: 'merchant_' + new Date().getTime(),
                name: test2, //product name으로 바꿔주기
                amount: test1,

                /////////////////////////////// 원화로 변경
                buyer_email: test4,
                buyer_name: test3,
                buyer_tel: test5,
                // buyer_addr: '서울특별시 강남구 삼성동',
                // buyer_postcode: '123-456',
                // m_redirect_url: 'https://www.yourdomain.com/payments/complete'
            }, function (rsp) {
                if (rsp.success) {
                    var msg = '결제가 완료되었습니다.';
                    msg += '고유ID : ' + rsp.imp_uid;
                    msg += '상점 거래ID : ' + rsp.merchant_uid;
                    msg += '결제 금액 : ' + rsp.paid_amount;
                    msg += '카드 승인번호 : ' + rsp.apply_num;
                } else {
                    var msg = '결제에 실패하였습니다.';
                }
                // 결제 확인

                if(msg == '결제에 실패하였습니다.'){
                    alert("결제에 실패하였습니다. 사용자가 결제를 취소하였습니다.");
                    location.href = "/main/";
                }
                else{
                    alert("결제가 완료되었습니다.");
                    location.href = 'complete/';
                }

            });
            $.ajax({
                type: 'POST',
                url:'/payment/complete',
                data : {test1:test1},
                success: function (result){}
            })
        })();
    </script>

</head>

<body>
</body>

{% endwith %}
{% endblock %}