shop/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = 'shop'

urlpatterns = [
    path('', landingpage, name="home"),
    path('envigoods/', envigoods, name="envigoods"),
    path('serviceintroduce/', serviceintroduce, name="serviceintroduce"),
    path('main/', restaurant_in_category, name='product_all'),
    path('<slug:category_slug>/', restaurant_in_category, name='restaurant_in_category'),
    path('main/<slug:restaurant_slug>/', product_in_restaurant, name='product_in_restaurant'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('sellerPage/register/', ProductRegister.as_view(), name='product_register'),

    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
    path('deletecomment/<int:comment_id>', deletecomment, name='deletecomment'),

]

shop/templates/shop/envigoods.html
{% extends 'base.html' %}
{% block title %}EnviGoods Page {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/envigoods.css' %}"/>


<style>
    #pagecolor {color: #2A6049;}
    #titlefont {
        color: white;
        font-weight: bold;
    }
    #my_modal {
        display: none;
        width: 400px;
        padding: 20px 60px;
        background-color: #fefefe;
        border: 1px solid #888;
        border-radius: 3px;
        text-align: center;
    }
    #my_modal .modal_close_btn {
        position: absolute;
        top: 10px;
        right: 15px;
    }
</style>


<div class="box-container">

    <div class="envi_word" style="position: relative; text-align: center;">
        <div class="envi_text" id="titlefont" style="position: absolute; z-index:2;">
            <br><br>
            <p style="font-size: 3rem;">위빙 굿즈샵</p>
            <p style="font-size: 1.3rem;">환경을 생각하는 친환경 제품판매를 하는 위빙 굿즈 샵</p>
        </div>
        <div style="position: relative;z-index: 1;">
            <img src="{% static 'img/leaves.jpg' %}" alt="enviword" style="width:100%; height:250px; filter: brightness(40%);">
        </div>
    </div>

    <div class="goods_card1">

        <div class="card" id="popup_open_btn1" style="width: 19rem;">
            <img src="{% static '/img/tumblr.jpg' %}" class="card-img-top" alt="tumblr" style="width:19rem; height:200px;">
            <div class="card-body">
              <h5 class="card-title" id="pagecolor" style="font-weight: bold;">친환경 텀블러</h5>
              <p class="card-text">환경을 생각한 텀블러 | <span id="pagecolor">10,000원</span></p>
              <p class="card-text">별점 | <span id="pagecolor">None 개 판매</span></p>
            </div>
          </div>

    </div>

    <div class="goods_card2">

        <div class="card" id="popup_open_btn2" style="text-align:center;width: 19rem;">
            <img src="{% static '/img/ecobag.png' %}" class="card-img-top" alt="..." style="width:19rem; height:200px;">
            <div class="card-body" style="text-align: center;">
              <h5 class="card-title" id="pagecolor" style="font-weight: bold;">친환경 에코백</h5>
              <p class="card-text">환경을 생각한 에코백 | <span id="pagecolor">5,000원</span></p>
              <p class="card-text">별점 | <span id="pagecolor">None 개 판매</span></p>
            </div>
          </div>

    </div>

    <div class="goods_card3">

        <div class="card" id="popup_open_btn3" style="text-align:center;width: 19rem;">
            <img src="{% static '/img/paperbag.jpg' %}" class="card-img-top" alt="..." style="width:19rem; height:200px;">
            <div class="card-body" style="text-align: center;">
              <h5 class="card-title" id="pagecolor" style="font-weight: bold;">친환경소재 종이가방</h5>
              <p class="card-text">환경을 생각한 종이가방 | <span id="pagecolor">4,000원</span></p>
              <p class="card-text">별점 | <span id="pagecolor">None 개 판매</span></p>
            </div>
          </div>

    </div>

</div>



<div id="my_modal">
    <p id="pagecolor" style="font-size: 1.5rem;">< 위빙 굿즈샵 ></p>
    <p>굿즈 서비스를 준비중입니다.</p>
    <a class="modal_close_btn" style="float:right;color: black;">X</a>
</div>

<script>
    function modal(id) {
        var zIndex = 9999;
        var modal = document.getElementById(id);

        // 모달 div 뒤에 희끄무레한 레이어
        var bg = document.createElement('div');
        bg.setStyle({
            position: 'fixed',
            zIndex: zIndex,
            left: '0px',
            top: '0px',
            width: '100%',
            height: '100%',
            overflow: 'auto',
            // 레이어 색갈은 여기서 바꾸면 됨
            backgroundColor: 'rgba(0,0,0,0.4)'
        });
        document.body.append(bg);

        // 닫기 버튼 처리, 시꺼먼 레이어와 모달 div 지우기
        modal.querySelector('.modal_close_btn').addEventListener('click', function() {
            bg.remove();
            modal.style.display = 'none';
        });

        modal.setStyle({
            position: 'fixed',
            display: 'block',

            // 시꺼먼 레이어 보다 한칸 위에 보이기
            zIndex: zIndex + 1,

            // div center 정렬
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            msTransform: 'translate(-50%, -50%)',
            webkitTransform: 'translate(-50%, -50%)'
        });
    }

    // Element 에 style 한번에 오브젝트로 설정하는 함수 추가
    Element.prototype.setStyle = function(styles) {
        for (var k in styles) this.style[k] = styles[k];
        return this;
    };

    document.getElementById('popup_open_btn1').addEventListener('click', function() {
        // 모달창 띄우기
        modal('my_modal');
    });
    document.getElementById('popup_open_btn2').addEventListener('click', function() {
        // 모달창 띄우기
        modal('my_modal');
    });
    document.getElementById('popup_open_btn3').addEventListener('click', function() {
        // 모달창 띄우기
        modal('my_modal');
    });
</script>

    
    
{% endblock %}

shop/templates/shop/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Webeing</title>
    <meta name="description" content="A page background effect where SVG shapes morph and transform on scroll"/>
    <meta name="keywords" content="background, svg, morph, animation, scroll, shape, web development, css, javascript"/>
    <meta name="author" content="Codrops"/>
    <link rel="shortcut icon" href="favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/landing.css' %}"/>

    <style>
        #fontgreen {
            color: #2CAE65;
        }

        #subtitle {
            font-size: 1.5rem;
            font-weight: 300%;
        }

        #subsubtitle {
            font-size: 1.1rem;
        }

        #p1 {
            font-family: 'Nanum Gothic Coding', monospace;
        }
    </style>

</head>


<body class="demo-2 loading" id="background_img">

<main>
    <div class="content content--fixed">

        <header class="codrops-header">

            <img src="{% static '/img/webeing.png'%}" alt="webeing" style="width:100px; height: 100px;">

            <h1 class="codrops-header__title" style="margin-top: 25px;">Webeing</h1>
        </header>

        <nav class="demos" style="margin-left: 30px;">
            <a title="facebook" href="https://www.facebook.com/We-being-100435421763637" target="_blanck">
                <img src="{% static '/img/facebook.png' %}" alt="facebook"
                     style="margin: 0 0 20px 10px; width:15px; height:30px;">
            </a>
            <br>
            <a title="instagram" href="https://www.instagram.com/we_being/" target="_blank">
                <img src="{% static 'img/instagram.png' %}" alt="instagram"
                     style="margin-bottom: 20px; width:30px; height:30px;">
            </a>
            <br>
            <a title="kakaotalk" href="http://pf.kakao.com/_sSYyxb" target="_blank">
                <img src="{% static 'img/kakaotalk.png' %}" alt="kakao"
                     style="margin-bottom: 20px; width:30px; height: 30px;">
            </a>
        </nav>

        <div>
            <a href="/main">
                <img src="{% static '/img/homebutton.png' %}" style="width:150px; float:right" alt="gotomain"/>
            </a>
        </div>

        <div class="deco deco--title">2020 Webeing service</div>

    </div>

    <div style="margin-left : 0px">
        <div class="content-wrap">
            <div class="content content--layout content--layout-2">
                <img class="content__img" src="{% static '/img/webeing.png' %}"
                     style="width:600px; height:600px;"
                     alt="Some image"/>
                <h3 class="content__title" id="titleho" style="font-size: 10rem">WEBEING</h3>
                <h4 class="content__desc" style="font-size:2rem;"><span id="fontgreen">초록 식문화</span>의 출발,<br>음식에
                    <span
                            id="fontgreen">환경</span>의 가치를<br>더하다</h4>
            </div>
        </div>

        <div class="content-wrap">
            <div class="content content--layout content--layout-1">
                <img class="content__img" src="{% static '/img/service1.png' %}" alt="Some image"/>
                <h3 class="content__title" id="titleho" style="padding-left: 15rem;">재고상품처리</h3>
                <p class="content__desc"><span id="subtitle">유통기한이 지난 재고상품을 처리할 때마다<br>생기는 고민</span>
                    <br><br>
                    <span id="subsubtitle">- 버려지는 수많은 음식들
                        <br>- 매번 낭비되는 비용들
                        <br>- 음식물 쓰레기로 인한 환경오염</span>
                </p>
            </div>
        </div>

        <div class="content-wrap">
            <div class="content content--layout content--layout-3">
                <img class="content__img" src="{% static  'img/service2.png' %}"
                     style="width:380px; height: 380px;"
                     alt="Some image"/>
                <h3 class="content__title" id="titleho" style="margin-top: 3rem;">합리적인 소비</h3>
                <p class="content__desc"><span id="subtitle">환경보호와 더불어 저렴한 가격으로 상품을 구매</span>
                    <br><br>
                    <span id="subsubtitle">- 원하는 상품의 합리적인 가격의 소비
                        <br>- 환경을 생각하는 착한 소비
                        <br>- 경제적, 시간적인 가계 부담 감소</span>
                </p>
            </div>
        </div>

        <section class="content content--related">
            <p class="content__info" style="float:right;"><strong><h2 style="font-size: 1.5rem;">1년간 국내 음식물 쓰레기
                발생량은</h2><br></strong></p>

            <div class="content__related-item">
                <img class="content__related-img" src="{% static '/img/service3-1.png' %}" style="width:30%;">
                <h3 class="content__related-title" style="font-size: 1.3rem;">온실가스</h3>
                <p class="content__info">하루 235만대의 차량주행시 배출되는 온실가스의 양과 동일합니다.</p>
            </div>

            <div class="content__related-item">
                <img class="content__related-img" src="{% static '/img/service3-2.png' %}" style="width:30%;">
                <h3 class="content__related-title" style="font-size: 1.3rem;">쓰레기 산</h3>
                <p class="content__info">연간 배출되는 음식물쓰레기의 양은 63빌딩 19채와 같습니다.</p>
            </div>

            <div class="content__related-item">
                <img class="content__related-img" src="{% static '/img/service3-3.png' %}" style="width:30%;">
                <h3 class="content__related-title" style="font-size: 1.3rem;">절감 효과</h3>
                <p class="content__info">음식물처리비용절감시 커피 5.5억잔, 서울 아파트 2만4천채를 구매할 수 있습니다.</p>
            </div>

        </section>

        <section class="content content--related" style="margin-top: 25rem;">
            <p class="content__info" style="float: left 50%;"><strong><h2 style="font-size: 1.5rem;">위빙에 선사하는 서비스</h2>
                <br></strong></p>

            <div class="content__related-item">
                <img class="content__related-img" style="width:30%;" src="{% static '/img/service4-1.png' %}">
                <h3 class="content__related-title" style="font-size: 1.3rem;">마감 할인</h3>
                <p class="content__info">정상적인 재고 음식들을 할인해서 소비자에게 연결해줌으로서 저렴한 가격에 구입을 할 수 있으며,<br>
                    더 나아가 버려질 수 있던 음식들의 낭비를 감소시킴으로서 환경 오염 등 여러사회적문제를 해결할 수 있을 것입니다.</p>
            </div>

            <div class="content__related-item">
                <img class="content__related-img" style="width:30%;" src="{% static '/img/service4-3.png' %}">
                <h3 class="content__related-title" style="font-size: 1.3rem;">환경 계좌</h3>
                <p class="content__info">위빙을 통하여 구매한 금액 중 일부를 환경에 기여한 금액으로 산정하여 환경 계좌에 적립될 예정입니다.<br>
                    적립된 금액은 위빙 굿즈를 구매하거나 음식 구매시 할인, 또는 환경을 위한 모금활동에 사용 할 수 있습니다.</p>
            </div>

            <div class="content__related-item">
                <img class="content__related-img" style="width:30%;" src="{% static '/img/service4-2.png' %}">
                <h3 class="content__related-title" style="font-size: 1.3rem;">위빙 굿즈</h3>
                <p class="content__info">환경 보호를 위한 위빙의 목표를 위하여 일회용품을 줄이기 위한 굿즈를 판매할 계획입니다.<br>
                    에코백, 텀블러를 시작으로 머그컵과 같은 상품까지 구입 할 수 있습니다.</p>
            </div>

        </section>

        <div class="content-wrap" style="margin-top: 30rem;">

            <ul style="line-height: 40px;">
                <div class="row">
                    <div class="col">
                        <div class="row" style="font-weight: bold; font-size: 25px;">
                            <p1>Information</p1>
                        </div>
                        <div class="row">
                            <p1>상호 : 위빙(Webeing)</p1>
                        </div>
                        <!-- <div class="row">
                            <p1>대표: 이상륜</p1>
                        </div> -->
                        <div class="row">
                            <p1>개인정보관리책임자 : 한승조</p1>
                        </div>
                        <div class="row">
                            <p1>개인정보담당자 : slowwvibes@gmail.com</p1>
                        </div>
                        <div class="row">
                            <p1>사업자등록번호 : 839-55-00602</p1>
                        </div>
                    </div>
                    <br>
                    <div class="col">
                        <div class="row" style="font-weight: bold; font-size: 25px;">
                            <p1>Address</p1>
                        </div>
                        <div class="row">
                            <p1>
                                경기도 성남시 수정구
                                창곡동 564 푸르지오5단지
                                상가 5B-102호
                            </p1>
                        </div>
                    </div>
                    <br>
                    <div class="col">
                        <div class="row" style="font-weight: bold; font-size: 25px;">
                            <p1>Developers</p1>
                        </div>
                        <div class="row">
                            <p1>한승조 인세훈 이찬규 김재욱 최진영</p1>
                        </div>
                    </div>
                    <br>
                    <div class="col">
                        <div class="row" style="font-weight: bold; font-size: 25px;">
                            <p1>Helpful Links</p1>
                        </div>
                        <div class="row">
                            <p1 style="color:white"><a href="/'tos_user_use'">이용약관</a></p1>
                        </div>
                        <div class="row">
                            <p1 style="color:white"><a href="{% url 'tos_user_private' %}">개인정보처리방침</a></p1>
                        </div>
                    </div>
                    <br>
                    <div class="col">
                        <div class="row" style="font-weight: bold; font-size: 25px;">
                            <p1>Contact Us</p1>
                        </div>
                        <div class="row">
                            <p1>phone : 010-9228-0236</p1>
                        </div>
                        <div class="row">
                            <p1>email : we-being@naver.com</p1>
                        </div>
                    </div>
                    <br>

                </div>

                <br>
                <div style="text-align: center;">
                    <p1>copyright by Webeing.</p1>
                </div>

            </ul>
        </div>
    </div>
</main>


</body>

</html>

shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% block title %}Restaurant Page{% endblock %}
{% block content %}
{% load static %}


<link rel="stylesheet" href="{% static 'css/product_list.css' %}"/>

<style>
    #restaurantfont {
        font-size: 180%;
        font-weight: bold;
    }

    #restaurant_location {
        font-size: 180%;
        font-weight: bold;
    }

    #green {
        font-size: 1.5rem;
        font-weight: bold;
        color: #2A6049;
    }

    #red {
        font-size: 1.5rem;
        font-weight: bold;
        color: red;
    }

    #bold {
        font-weight: bold;
    }

    th, td {
        padding: 10px;
    }

    #my_modal {
        display: none;
        width: 400px;
        padding: 20px 60px;
        background-color: #fefefe;
        border: 1px solid #888;
        border-radius: 3px;
        text-align: center;
    }

    #my_modal .modal_close_btn {
        position: absolute;
        top: 10px;
        right: 15px;
    }
</style>

<!-- <div class="box-container"> -->

<div class="store" id="box-layout" style="margin: 50px 0px 50px 0px; background-color: white">

    <div class="store-in">

        <div class="storepic">
            <div class="card-image"><img style="max-width: 100%" src="{{current_restaurant.image.url}}"></div>
        </div>

        <div class="storeinfo">
            <p id="restaurantfont">{{current_restaurant.name}}</p>
            <p>전화번호 | {{current_restaurant.call_number}}</p>
            <p>지도 | <a href="#restaurant_location" style="color:black">위치보기</a></p>
        </div>

    </div>

</div>

<div style="margin-bottom:50px;">

    <p><span id="restaurantfont">오늘의 상품</span><span style="float: right;">오늘 판매하는 상품만 등록합니다.</span></p>

    <!-- Up to 3 menus -->
    {% for product in products %}

    <div class="menu-in" id="box-layout" style="background-color: white">

        <div class="menupic">
            <p class="text-center">
                <img class="card-img-top" src="{{product.image.url}}" alt="restaurant Image"
                     style=" height: 150px;width: 150px; ">
            </p>
        </div>

        <div class="menuinfo">
            <ul style="list-style: none;">
                <br>
                <li id="restaurantfont">{{product.name}}</li>
                <br>
                <li><span id="green">{{product.origin_price}}원 </span> → <span id="red">{{product.price}}원<span
                        id="green"> ( {{product.discount|floatformat:"0"}} % )</span></span></li>
                <div onload="boxlayout()">
                    <li id="result"></li>
                </div>
            </ul>
        </div>

        <div class="cartbutton"><br>
            <form action="{% url 'cart:product_add' product.id  %}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
                {% if request.user.is_authenticated %}
                <input type="submit" class="btn btn-success btn-sm" value="카트 추가" style="margin-top:20px;">
                {% else %}
                <div onclick="
                    var a= alert('위빙서비스를 이용하시려면 로그인을 해주세요!');"><input class="btn btn-success btn-sm" value="카트 추가"
                                                                      style="margin-top:20px;">
                </div>
                {% endif %}
            </form>
        </div>

    </div>
    {% endfor %}

    {% if products|length == 0 %}
    <div style="margin: 2rem;">
        <p id ="no_restaurant" style="font-size:1.5rem;">상품을 준비중입니다.</p>
    </div>
    {% endif %}

</div>

<div style="margin-bottom:50px;">
    <table class="table table-hover">

        <thead>
        <tr style="background-color: white;">
            <th>날짜</th>
            <th>댓글</th>
            <th>작성자</th>
            <th></th>
        </tr>
        </thead>

        <tbody style="background-color: white;">
        {% for post in page_posts %}
        <tr>
            <td id="blog_date">{{post.pub_date}}</td>
            <td id="blog_title" style="width : 500px;">{{post.body}}</td>
            <td id="blog_owner">{{post.owner}}</td>
            <td>

                {% if user.email == post.owner %}
                <button class="btn btn-success" onclick="location.href='{% url 'shop:deletecomment' post.id %}'">삭제하기
                </button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="paginator" style="text-align: center">
        {% if page_posts.has_previous %}
        <a href="?page=1" style="color: black;">첫페이지</a>
        <a href="?page={{page_posts.previous_page_number}}" style="color: black;">< 이전</a>
        {% endif %}
        <span>{{page_posts.number}}</span>
        <span>of<span>
                    <span>{{page_posts.paginator.num_pages}}</span>

                {% if page_posts.has_next %}
                    <a href="?page={{page_posts.next_page_number}}" style="color: black;">다음 ></a>
                    <a href="?page={{page_posts.paginator.num_pages}}" style="color: black;">마지막페이지</a>
                {% endif %}
    </div>
    {% if request.user.is_authenticated %}
    <form method="POST">
        {% csrf_token %}

        <h4>리뷰 달기</h4>
        <div class="row">
            <div class="col-sm-11">
                <textarea id="newpost_body" cols=120 rows=2 name="body"
                          style="width:100%; border: 1px solid lightgray;"></textarea>
            </div>
            <div class="col-sm-1">

                <input style=" text-align: right;" class="btn btn-dark" type="submit" value="제출">

            </div>
        </div>
    </form>
    {% else %}

    <h4>리뷰 달기</h4>
    <div class="row">
        <div class="col-sm-11">
                <textarea id="newpost_body" cols=120 rows=2 name="body"
                          style="width:100%; border: 1px solid lightgray;"></textarea>
        </div>
        <div class="col-sm-1">
            <div onclick="
                    var a= alert('위빙서비스를 이용하시려면 로그인을 해주세요!');"><input style=" text-align: right;" class="btn btn-dark" type="submit"
                                             value="제출"></div>
        </div>
    </div>
    {% endif %}
</div>

<div class="storelocation" id="margin" style="margin-bottom:50px;">

    <p><span id="restaurant_location">매장 위치</span></p>

    <!-- for map -->
    <div id="map" style="width:100%;height:500px;"></div>


</div>

<div class="storeinfo" style="margin-bottom:50px; ">

    <p><span id="restaurantfont">매장 정보</span></p>

    <div id="box-layout" style="background-color: white">

        <table>

            <colgroup>
                <col width="35%"/>
                <col width="*"/>
            </colgroup>

            <tr>
                <td>영업시간</td>
                <td>{{current_restaurant.open_time}}</td>
            </tr>

            <tr>
                <td>전화번호</td>
                <td>{{current_restaurant.call_number}}</td>
            </tr>

            <tr>
                <td>주소</td>
                <td>
                    <div id="address">{{current_restaurant.location}}</div>
                </td>
            </tr>

        </table>

    </div>

</div>

<div class="storeowner" style="margin-bottom:50px;">

    <p><span id="restaurantfont">사업자 정보</span></p>

    <div id="box-layout" style="background-color: white">

        <table>

            <colgroup>
                <col width="45%"/>
                <col width="*"/>
            </colgroup>

            <tr>
                <td>상호명</td>
                <td>{{current_restaurant.name}}</td>
            </tr>

            <tr>
                <td>사업자등록번호</td>
                <td>{{current_restaurant.business_number}}</td>
            </tr>

        </table>

    </div>

</div>

<div class="foodinfo" style="margin-bottom:50px;">

    <p><span id="restaurantfont">원산지 정보</span></p>

    <div id="box-layout" style="background-color: white">
        <p>{{current_restaurant.food_origin}}</p>
    </div>

</div>

<div id="my_modal">
    <p id="pagecolor" style="font-size: 1.5rem;">< 위빙 서비스안내 ></p>
    <p>위빙서비스를 이용하시려면 로그인을 해주세요!</p>
    <a class="modal_close_btn" style="float:right;color: black;">X</a>
</div>

<script>
    function boxlayout() {
        var origin_price = document.getElementById("red").innerHTML;
        var price = document.getElementById("green").innerHTML
        result = parseInt(origin_price) / parseInt(price)
        document.getElementById("result").innerHTML = result
    }


</script>

<script>
    var address = document.getElementById("address").innerHTML;

    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center: new kakao.maps.LatLng(127.140083, 37.4676097), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();

    // 주소로 좌표를 검색합니다
    geocoder.addressSearch(address, function (result, status) {

        // 정상적으로 검색이 완료됐으면
        if (status === kakao.maps.services.Status.OK) {

            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });

            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0;">{{current_restaurant.name}}</div>'
            });
            infowindow.open(map, marker);

            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        }
    });

</script>
<script>
    function modal(id) {
        var zIndex = 9999;
        var modal = document.getElementById(id);

        // 모달 div 뒤에 희끄무레한 레이어
        var bg = document.createElement('div');
        bg.setStyle({
            position: 'fixed',
            zIndex: zIndex,
            left: '0px',
            top: '0px',
            width: '100%',
            height: '100%',
            overflow: 'auto',
            // 레이어 색갈은 여기서 바꾸면 됨
            backgroundColor: 'rgba(0,0,0,0.4)'
        });
        document.body.append(bg);

        // 닫기 버튼 처리, 시꺼먼 레이어와 모달 div 지우기
        modal.querySelector('.modal_close_btn').addEventListener('click', function () {
            bg.remove();
            modal.style.display = 'none';
        });

        modal.setStyle({
            position: 'fixed',
            display: 'block',

            // 시꺼먼 레이어 보다 한칸 위에 보이기
            zIndex: zIndex + 1,

            // div center 정렬
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            msTransform: 'translate(-50%, -50%)',
            webkitTransform: 'translate(-50%, -50%)'
        });
    }

    // Element 에 style 한번에 오브젝트로 설정하는 함수 추가
    Element.prototype.setStyle = function (styles) {
        for (var k in styles) this.style[k] = styles[k];
        return this;
    };

    document.getElementById('popup_open_btn4').addEventListener('click', function () {
        // 모달창 띄우기
        modal('my_modal');
    });
    document.getElementById('popup_open_btn5').addEventListener('click', function () {
        // 모달창 띄우기
        modal('my_modal');
    });
    document.getElementById('popup_open_btn3').addEventListener('click', function () {
        // 모달창 띄우기
        modal('my_modal');
    });
</script>
{% endblock %}